server:
  port: 8080
datasource:
  driverName: mongodb
  host: localhost
  port: 27017
  database: mxall
  username: bilin
  password: 123456
  charset: utf8
  loc: Asia/Shanghai
redissource:
  driverName: redis
  host: localhost
  port: 6379
  password: ""
  DB: 0
